FROM node:16-alpine

WORKDIR /usr/app

COPY package.json .
RUN npm install
RUN mkdir -p /usr/app/node_modules/.cache && chown -R node:node /usr/app/node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]